# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/qtbigwork.icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        widget.setWindowIcon(icon)
        widget.setStyleSheet("")
        self.verticalLayoutWidget = QtWidgets.QWidget(widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 40, 281, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.user = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.user.setMinimumSize(QtCore.QSize(279, 60))
        self.user.setStyleSheet("border-image: url(:/resource/background.png);\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 8px;font-family: 微软雅黑;\n"
"")
        self.user.setAlignment(QtCore.Qt.AlignCenter)
        self.user.setObjectName("user")
        self.verticalLayout.addWidget(self.user)
        self.password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password.setMinimumSize(QtCore.QSize(279, 60))
        self.password.setStyleSheet("border-image: url(:/resource/background.png);")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.login_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.login_button.setMinimumSize(QtCore.QSize(200, 40))
        self.login_button.setStyleSheet("border-image: url(:/resource/background.png);")
        self.login_button.setObjectName("login_button")
        self.verticalLayout.addWidget(self.login_button)
        self.label = QtWidgets.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(10, 0, 381, 291))
        self.label.setStyleSheet("border-image: url(:/resource/loginbackground.jpeg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.verticalLayoutWidget.raise_()

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "众生之门"))
        self.user.setPlaceholderText(_translate("widget", "用户名"))
        self.password.setPlaceholderText(_translate("widget", "密码"))
        self.login_button.setText(_translate("widget", "登陆"))
import main_rc
