# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(999, 605)
        Form.setStyleSheet("")
        self.Backgroundlabel = QtWidgets.QLabel(Form)
        self.Backgroundlabel.setGeometry(QtCore.QRect(11, 11, 977, 583))
        self.Backgroundlabel.setStyleSheet("border-image: url(:/resource/background.png);")
        self.Backgroundlabel.setText("")
        self.Backgroundlabel.setObjectName("Backgroundlabel")
        self.closeBtn = QtWidgets.QPushButton(Form)
        self.closeBtn.setGeometry(QtCore.QRect(890, 60, 31, 31))
        self.closeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeBtn.setStyleSheet("    color:black;\n"
"    box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 8px;font-family: 微软雅黑;\n"
"")
        self.closeBtn.setObjectName("closeBtn")
        self.friendslistWidget = QtWidgets.QListWidget(Form)
        self.friendslistWidget.setGeometry(QtCore.QRect(150, 110, 251, 439))
        self.friendslistWidget.setStyleSheet("font-family: 微软雅黑;\n"
"background-color: rgb(245, 245, 245);")
        self.friendslistWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.friendslistWidget.setObjectName("friendslistWidget")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(60, 55, 91, 494))
        self.frame.setStyleSheet("background-color: rgb(108, 108, 108);\n"
"border-radius: 10px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.avatarlabel = QtWidgets.QPushButton(self.frame)
        self.avatarlabel.setGeometry(QtCore.QRect(20, 30, 50, 50))
        self.avatarlabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.avatarlabel.setStyleSheet("")
        self.avatarlabel.setText("")
        self.avatarlabel.setObjectName("avatarlabel")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(390, 55, 20, 495))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Searchbar = QtWidgets.QLineEdit(Form)
        self.Searchbar.setGeometry(QtCore.QRect(162, 70, 221, 31))
        self.Searchbar.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"    color:white;\n"
"    box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 8px;font-family: 微软雅黑;\n"
"")
        self.Searchbar.setObjectName("Searchbar")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(310, 130, 71, 71))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 301, 241))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 8px;font-family: 微软雅黑;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_mask = QtWidgets.QLabel(Form)
        self.label_mask.setGeometry(QtCore.QRect(400, 116, 531, 431))
        self.label_mask.setStyleSheet("font-family: 微软雅黑;\n"
"background-color: rgb(238, 238, 238);")
        self.label_mask.setObjectName("label_mask")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(400, 100, 521, 441))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.currentChatFriendName = QtWidgets.QLabel(Form)
        self.currentChatFriendName.setGeometry(QtCore.QRect(410, 70, 241, 31))
        self.currentChatFriendName.setStyleSheet("font-size:24px;font-family: 微软雅黑;\n"
"")
        self.currentChatFriendName.setObjectName("currentChatFriendName")
        self.Backgroundlabel.raise_()
        self.friendslistWidget.raise_()
        self.frame.raise_()
        self.closeBtn.raise_()
        self.line.raise_()
        self.Searchbar.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label_mask.raise_()
        self.gridLayoutWidget_2.raise_()
        self.currentChatFriendName.raise_()

        self.retranslateUi(Form)
        self.closeBtn.clicked.connect(Form.close)
        self.closeBtn.clicked.connect(self.closeBtn.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.closeBtn.setText(_translate("Form", "X"))
        self.Searchbar.setText(_translate("Form", "搜索"))
        self.label_mask.setText(_translate("Form", "选择左边用户进行聊天"))
        self.currentChatFriendName.setText(_translate("Form", "罗小白"))
import main_rc
